version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nova-postgres
    env_file:
      - ./nova-booking-backend/.env
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - PGTZ=Asia/Ho_Chi_Minh
    ports:
      - "5435:5432"
    volumes:
      - nova_pg_data:/var/lib/postgresql/data
    networks:
      - nova-network
    restart: always
    # Thêm healthcheck để "condition: service_healthy" ở dưới hoạt động được
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d nova_booking_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./nova-booking-backend
      dockerfile: Dockerfile
    container_name: nova-backend
    ports:
      - "3001:3001"
    volumes:
      - ./nova-booking-backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://root:rootpassword@db:5432/nova_booking_db?schema=public
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      db:
        condition: service_healthy
    networks: # QUAN TRỌNG: Phải có dòng này
      - nova-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nova-frontend
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - nova-network
    restart: always

networks:
  nova-network:
    driver: bridge

volumes:
  nova_pg_data: